name: Build Docker image

on:
  [push, workflow_dispatch]

env:
  DOCKER_USERNAME: vroniu
  DOCKER_IMAGE_NAME: jenkins-agent

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat version)"
    - name: Login to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
    - name: Output build parameters
      run: echo "Building image ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}"; echo "Version ${{ steps.getversion.outputs.version }}"
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./${{env.WORKDIR}}
        push: true
        tags: |
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.getversion.outputs.version }}
          ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}
    
